version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-react-app .
      - docker tag my-react-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/myfirstproject:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/myfirstproject:latest
artifacts:
  files:
    - '**/*'
  discard-paths: yes

env:
  variables:
    AWS_ACCOUNT_ID: "739275479532"
    AWS_DEFAULT_REGION: "us-east-1"
  image: aws/codebuild/standard:5.0
  compute_type: BUILD_GENERAL1_SMALL

